site_name: Lesgo!
site_description: A lightweight node.js serverless framework
site_author: Sufiyan Rahmat
site_url: https://reflex-media.github.io/lesgo-docs/

repo_name: reflex-media/lesgo
repo_url: https://github.com/reflex-media/lesgo
extra:
  repo_icon: github
  version:
    provider: mike
    default: stable

copyright: Copyright &copy; 2019 Reflex Media

theme:
  name: material
  palette:
    primary: white
    accent: orange
  logo:
    icon: cloud
  feature:
    tabs: false
  extra_css:
    - "stylesheets/extra.css"
  custom_dir: overrides

extra_css:
  - "stylesheets/extra.css"

use_directory_urls: true

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false

nav:
  - Prologue: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Directory Structure: getting-started/structure.md
      - Deployment: getting-started/deployment.md
      - Available Scripts: getting-started/available-scripts.md
  - The Basics:
      - Middleware: basics/middleware.md
      - Error Handling: basics/error-handling.md
      - Logging: basics/logging.md
  - Digging Deeper:
      - Cache: advance/cache.md
      - Database: advance/database.md
      - Helpers: advance/helpers.md
      - Object Store: advance/object-store.md
      - Queues: advance/queues.md
      - Task Scheduling: advance/task-scheduling.md
      - Unit Tests: advance/unit-tests.md
      - Full-Text Search: advance/full-text-search.md
      - Typescript: advance/typescript.md
  - Security:
      - VPC: security/vpc.md
  - Contributing: contributing.md
